### PR TITLE
Add missing translations for type select

### PR DESCRIPTION
**Pull request by marcreichel**
Adds missing translations for the type select

### CODE REVIEW

**Comment by marcreichel** [comment]
@classic-o I was about to push the built assets (`dist` directory) because I forgot 😄 Please keep in mind to build them first before publishing a new version 🙂

**Comment by marcreichel** [comment]
Or I can push them so you can merge them as well 👍🏼

**Comment by classic-o** [comment]
Thank you, I will do it

**Comment by marcreichel** [comment]
Thanks 🙂  Great package and thanks for the quick response/merge(s) 🙂

**Comment by classic-o** [comment]
Added build in 1.0.7

**Comment by marcreichel** [comment]
Thanks man 🎉

**Pull request merged**
